<main>
  <section>
    <b>Welcome to Prompt Ultra !</b>

    <p>
      This browser-based app allows you to automatically label textual datasets
      using Large Language Models (LLMs) with your ChatGPT <a
        href="https://help.openai.com/en/articles/7039783-how-can-i-access-the-chatgpt-api"
        >API key</a
      >.
      <!-- Read the companion paper <a href="https://arxiv.org/abs/2407.10645">here</a>. -->
    </p>
    <p>Here are the different features of Prompt Ultra:</p>
    <ul>
      <li>
        <b>EVÅL</b>: You can upload an unlabelled dataset and label it by
        providing custom instructions to an LLM. You can also upload an already
        labelled dataset to evaluate the accuracy of the labels generated by
        your instructions.
      </li>
      <li>
        <b>ØPTIM</b>: Start by uploading an already labelled dataset and
        providing a set of initial instructions. The app uses a genetic
        algorithm to create and test successive generations of new instructions.
        It selects the instructions that produce the most accurate labels. At
        the end of the optimization process, the app outputs the best
        instructions discovered.
      </li>
      <li>
        <b>SPLËT</b>: This convenience feature allows you to randomly divide a
        dataset into two separate datasets.
      </li>
      <li>
        <b>KLEAR CÄCHE</b>: API calls are stored by default so that results are
        not lost upon closing the tab. This button clears the cache.
      </li>
      <li>
        <b>D.SKÖNNECT</b>: Your OpenAI API key is stored by the browser. You can
        delete it from the browser's memory using this button (only appears once
        you have entered a valid key).
      </li>
    </ul>
  </section>
</main>

<style>
  section {
    max-width: 100%;
    width: 600px;
    margin: auto;
  }
</style>
